[package]
name = "guessing_games_yarn_spinner"
version = "0.1.0"
edition = "2021"
description = "A fun game where you guess what number the computer has chosen."
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.8.5"
